name: CI

on: [push]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL}}

jobs:
  skipci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[skip ci] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  build:

    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: build Dockerfile
        run: |
          IMAGE_NAME=test_container:${GITHUB_REF#refs/heads/} # docker imageの名前とそのタグ、${GITHUB_REF#refs/heads/}はブランチ名を取得する
          docker build .

     # - name: run test
        # TODO: juliaのテストを走らせるコマンドをかく
        # run: |
          # docker run ${IMAGE_NAME} \
          # julia -e"using Base; Base.runtests(tests=["all"]; ncores=ceil(Int, Sys.CPU_THREADS / 2), exit_on_error=false, revise=false, [seed])"

      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
